---
- hosts: routers
  name: Install software on router
  gather_facts: true

  tasks:
    - name: Install iptables
      become: true
      apt:
        name: iptables
        update_cache: true
    - name: Test iptables
      command: iptables --version
      environment:
        PATH: /usr/sbin:${PATH}
      register: iptables_test

    - debug: 
        var: iptables_test.stdout

    - name: Allow IP forwarding in kernel
      become: true
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"

  # - name: Set iptables rules for IP forwarding
  #   become: true
  #   iptables:
  #     table: nat
  #     chain: POSTROUTING
  #     out_interface: enp0s5
  #     jump: MASQUERADE

- hosts: pc
  name: Install nginx for testing
  gather_facts: true

  roles:
    - role: geerlingguy.nginx
      become: true
