---
- hosts: router
  name: Install software on router
  gather_facts: true

  tasks:
    - name: Install iptables
      become: true
      apt:
        name: iptables
        update_cache: true
    - name: Test iptables
      command: iptables --version
      environment:
        PATH: /usr/sbin:${PATH}
      register: iptables_test

    - debug: 
        var: iptables_test.stdout

    - name: Install dependecies
      become: true
      ansible.builtin.package:
        name:
          - network-manager
        state: present

    - name: Set static IP
      become: true
      nmcli:
        conn_name: my-eth1
        ifname: eth1
        type: ethernet
        ip4: 10.0.0.1
        gw4: 10.0.0.1
        state: present

- hosts: pc
  name: Install nginx for testing
  gather_facts: true

  roles:
    - role: geerlingguy.nginx
      become: true
